# Core
# CONFIG_NATIVE_SIM=y
CONFIG_SENSOR=y
CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_PRINTK=y
CONFIG_LOG_BUFFER_SIZE=8192

# Disable hardware specific
CONFIG_EMUL=y
CONFIG_I2C=y
CONFIG_I2C_EMUL=y

# GPIO Simulation
CONFIG_GPIO=y
CONFIG_GPIO_EMUL=y

# ADC Simulation
CONFIG_ADC=y
CONFIG_ADC_EMUL=y

# Simulated sensors
CONFIG_SENSOR=y
CONFIG_MS5607=y
CONFIG_BME280=y
# CONFIG_MS5607_EMUL=y
# CONFIG_BME280_EMUL=y

# GNSS (sim-fed)
CONFIG_GNSS=y
CONFIG_GNSS_SATELLITES=y
